name: Build

on:
  push:
    paths-ignore:
      - 'docs/*/**'
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc-version:
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.2"
          - "9.10.1"

    steps:
    - uses: actions/checkout@v4

    - name: Install cabal/ghc
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: '3.12.1.0'
    
    - name: Generate freeze file
      run: |
        cabal update
        cabal configure --disable-optimization --enable-tests
        cabal freeze

        # Exclude the timestamp of Hackage index update from our cache key, to
        # avoid invalidating cache too often.
        # This idea comes from github.com/jaspervdj/hakyll
        sed '/^index-state: /d' cabal.project.freeze > dependencies-versions
    
    - name: Cache cabal work
      uses: actions/cache@v4
      with:
        path: |
          dist-newstyle
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('dependencies-versions', 'cabal.project.local') }}-cabal-install
    
    - name: Build dependencies
      run: |
        cabal build all --only-dependencies
    
    - name: Build beam packages
      run: |
        cabal build all
        
    - name: Run tests
      run: |
        cabal test all